
networks:
  tpr_net:

services:
  frontend:
    networks:
      - tpr_net
    build:
      context: ./frontend
      args:
        BASE_URL: 'http://localhost:8000'
    ports:
      - '9000:80'
    depends_on:
      - backend

  backend:
    networks:
      - tpr_net
    build: ./backend
    restart: always
    command: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./materials:/materials
    environment:
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - LAB2_BACKEND_URL=http://host.docker.internal:8003/lab2
    depends_on:
      - migrate

  db:
    image: postgres:latest
    restart: always
    networks:
      - tpr_net
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mephisrw
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - tpr_net
    volumes:
      - ./backend/schema:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@db:5432/mephisrw?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: { }
