name: deploy on origin server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy_backend:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ debian-10 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Verify dependencies
        run: cd backend && go mod verify

      - name: Build
        run: cd backend && go build -tags 'netgo' -ldflags "-s -w -extldflags -static" cmd/main.go

      - name: Run go vet
        run: cd backend && go vet ./...

      - name: SSH save only
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: ${{ github.workspace }}/backend/main
          remote: ${{ secrets.BACKEND_PATH_ONLY_TO_SAVE }}
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          pre_upload: echo "This will be executed before the upload!"
          post_upload: echo "This will be executed after the upload!"
          ssh_options: -o StrictHostKeyChecking=no
          scp_options: -v

      - name: SSH mv binary file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            mv ${{ secrets.BACKEND_PATH_ONLY_TO_SAVE }} ${{ secrets.BACKEND_PATH }}


  build_and_deploy_frontend:
    needs: build_and_deploy_backend
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ debian-10 ]
    steps:
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install npm
        run: |
          cd frontend && npm install

      - name: Build
        run: |
           cd frontend && npm run build

      - name: SSH into server and deploy
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: ${{ github.workspace }}/frontend/dist/spa/*
          remote: ${{ secrets.FRONTEND_PATH }}
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          pre_upload: echo "This will be executed before the upload!"
          post_upload: echo "This will be executed after the upload!"
          ssh_options: -o StrictHostKeyChecking=no
          scp_options: -v