package table_name

const (
	UsersTable              = "users"
	SeminariansTable        = "seminarians"
	LecturersTable          = "lecturers"
	StudentsTable           = "students"
	GroupsTable             = "groups"
	LaboratoryMarkTable     = "laboratory_marks"
	LaboratoryTable         = "laboratory_works"
	ExternalLaboratoryTable = "external_laboratory_works"
	CurriculumTable         = "curriculums"
	DisciplinesTable        = "disciplines"
	SeminarVisitingTable    = "seminar_visiting"
	LessonVisitingTable     = "lesson_visiting"
	SeminarsTable           = "seminars"
	LessonsTable            = "lessons"
	SeminariansGroupsTable  = "seminarian_groups"
	DigitalGuideTable       = "digital_materials"
	DigitalDisciplineTable  = "digital_discipline"
	SectionLabs             = "section_lab"
	LaboratoryDateTable     = "laboratory_date"
	FilesPathTable          = "file_path"
	ExamTable               = "exams"
	LessonDateTable         = "lessons_date"
	TestsMarkTable          = "test_marks"
	TestsTable              = "tests"
	TestsDateTable          = "tests_date"
	SectionTable            = "sections"
	ThemesTable             = "themes"
	QuestionsTable          = "questions"
	AnswersTable            = "answers"
	ThemeQuestionsTable     = "theme_questions"
	SectionTests            = "section_test"
	TestsThemesTable        = "test_themes"
)
